config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  
  devise_for :users, :path => "accounts"

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :ideas do
    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end

    member do
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
=begin
      collection do
        get 'tab_active'
        get 'tab_hold'
        get 'tab_complete'
        get 'tab_all'
      end

      member do
        post :update_task
        get :more_less
      end
=end
    end

    member do
      post :update_status
      post :remove_category
    end
  end

  resources :tasks do
    
    collection do
      get 'tab_active'
      get 'tab_hold'
      get 'tab_complete'
      get 'tab_all'
    end

    member do
      post :update_task
      get :more_less
      get :show_children
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
    end

    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end
  end

  resources :categories do
    resources :notes do
      :notes
    end
  end

  resources :notes do
    resources :notes do
      :notes
    end
  end

  resources :jots do
    member do
      get :move_up
      get :move_down
      get :to_new_idea
      post :to_new_task
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :taskable, polymorphic: true

  acts_as_list scope: :taskable
  
  has_many :tasks,-> { order("position ASC") }, as: :taskable, dependent: :destroy
  has_many :notes, as: :notable, dependent: :destroy
  has_many :idea_links, as: :idea_linkable, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of :name, case_sensitive: false, scope: [:taskable_id]
  validates :status, :inclusion => { :in => %w(Hold Active Complete) }
  validates :percent_complete, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  before_validation :ensure_percent_complete_has_value, :ensure_status_has_value
  
  #extend FriendlyId
  #friendly_id :slug_candidates, use: :slugged

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

  def task_child?
    if self.taskable.is_a? Task
      true
    else
      false
    end
  end

  def over_due?
    
    if self.finish_date  && self.status == "Active"
      if self.finish_date < Time.now
        true
      else
        false
      end  
    else
      false
    end
  end

  protected
    def slug_candidates
      [
        :name,
        [:name, :taskable_type],
        [:name, :taskable_type, :taskable_id],
        [:name, :taskable_type, :taskable_id, :id]
      ]
    end

    def ensure_percent_complete_has_value
      self.percent_complete ||= 0
    end

    def ensure_status_has_value
      self.status ||= "Hold"
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include LoadChildren
  before_action :authenticate_user!
  respond_to :js, :html
  before_action :load_taskable, only: [:move_down, :move_up, :new, :create, :edit, :update, :destroy, :update_task, :more_less ]
  before_action :set_task, only: [:move_down, :move_up, :show_children, :destroy, :edit, :update, :update_task, :more_less]
  
  def new
    @task = Task.new 
    @task.user_id = current_user.id
  end

  def show
    @parent = Task.find(params[:id])
    load_children(@parent)
  end

  def create
    @task = @taskable.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "You created a new task."
    else
      flash[:danger] = "Something went wrong, try again."
      render :edit
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html {@parent = @task; load_children(@parent); flash[:success] = "Successfully updated task."; render :show }
        format.js 
        flash[:success] = "Successfully updated task."
      else
        format.html {@parent = @task; load_children(@parent); flash[:danger] = "Something went wrong, try again."; render :show }
        format.js    
        flash[:danger] = "Something went wrong, try again."
      end
    end
  end

  def destroy
    if @task.destroy
      flash[:success] = "Task removed."
    else
      flash[:danger] = "Failed to remove task."
    end
  end

  def update_task
    if params[:percent_complete] == 100 || params[:status] == "Complete"
      percent_complete = 100
      status = "Complete"
      completion_date = Time.now
      finish_date = params[:finish_date]
    else 
      percent_complete = params[:percent_complete]
      status = params[:status]
      completion_date = params[:completion_date]
      finish_date = params[:finish_date]
    end

    if @task.update(percent_complete: percent_complete, status: status, completion_date: completion_date, finish_date: finish_date)
      flash[:success] = "You successfully updated a task"
    else
      flash[:danger] = "Something went wrong, try again."
    end
  end

  def more_less

  end

  def show_children

  end

  def move_up
    
    if @@tab == "All"
      fail = @task.first?
    
    else
      status = @task.status
      next_same_status = @task.higher_items.where(status: status).last
      @task_position = @task.position

      if next_same_status
        next_position = next_same_status.position 
        
        if @task_position - next_position  > 1
          @above_task = @task.higher_item
        else
          @above_task = @task
        end

        fail = false
      else
        fail = true
      end
    end
    
    if fail
      flash[:danger] = "Task is already at the top."
      render nothing: true
    else
      case @@tab
      when "All"
        @task.move_higher
        @next = @task.lower_item
        @above_task = @task
      else
        @next = next_same_status
        @next.set_list_position(@task_position)
        @task.insert_at(next_position)
      end
      flash[:success] = "Task moved up list."
    end
  end

  def move_down

    if @@tab == "All"
      fail = @task.last?
    
    else
      status = @task.status
      next_same_status = @task.lower_items.where(status: status).first
      @task_position = @task.position

      if next_same_status
        next_position = next_same_status.position 
        
        if next_position - @task_position > 1
          @above_task = @task.lower_item
        else
          @above_task = @task
        end

        fail = false
      else
        fail = true
      end
    end
    
    if fail
      flash[:danger] = "Task is already at the bottom."
      render nothing: true
    else
      case @@tab
      when "All"
        @task.move_lower
        @next = @task.higher_item
        @above_task = @task
      else
        @next = next_same_status
        @next.set_list_position(@task_position)
        @task.insert_at(next_position)
      end
      flash[:success] = "Task moved up list."
    end
  end

  def tab_all
    @@tab = "All"
  end

  def tab_active
    @@tab = "Active"
  end

  def tab_hold
    @@tab = "Hold"
  end

  def tab_complete
    @@tab = "Complete"
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def load_taskable

      if params[:idea_id]
        @taskable = Idea.friendly.find(params[:idea_id])
      elsif params[:task_id]
        @taskable = Task.find(params[:task_id])
      end
    end

    def task_params
      params.require(:task).permit(:id, :name, :description, :assigned_by, :assigned_to, :user_id, :percent_complete, :start_date, :finish_date, :completion_date, :status, :slug, :idea_id, :task_id)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def taskable_link(type, id)
    taskable_path = type.constantize.find(id)
    link_to "Link to Parent", taskable_path
  end

  def tasks_percent_complete_total(tasks)
    if tasks.count != 0
      sum_percent_complete = 0
      
      tasks.each do |task|
        sum_percent_complete += task.percent_complete
      end

      (sum_percent_complete / tasks.count).to_i
    else
      0
    end
  end
  
  def row_class_task(task)
    case task.status
    when "Hold"
      return "row-warning"
    when "Complete"
      return "row-info"
    else
      return "row-success"
    end
  end
end

app/views/tasks/_form.html.haml
- modal ||= false
- remote = modal ? true : false
- data_model = task.id ? "edit_task_#{task.id}" : "new_task"
- route = modal ? [parent, task] : task
= bootstrap_form_for(route, layout: :inline, remote: remote, html: { role: :form, 'data-model' => "#{data_model}" }) do |f|
  = f.text_field :name
  = f.text_area :description
  = f.select :status, options_for_select([["Hold"], ["Active"], ["Complete"]]), { class: "selectpicker" }
  = f.number_field :percent_complete
  = f.date_field :start_date, class: 'form-control'
  = f.date_field :finish_date, class: 'form-control'
  = f.date_field :completion_date, class: 'form-control'
  = f.hidden_field :user_id, value: current_user.id
  = f.button class: "btn btn-success"
  = link_to "Cancel", :back, {:class=>"btn btn-default"}

app/views/tasks/_task.html.haml
.row.task-grid{:id => "task_#{task.id}", 'data-type' => "#{task.status}", class: "#{row_class_task(task)}" }
  = bootstrap_form_tag url: update_task_task_path(task.id), remote: true, layout: :inline do |f|
    .s2.l2
      .s1.l1
        - if task.tasks.count > 0
          = link_to show_children_task_path(task.id), remote: true do
            %span.glyphicon.glyphicon-plus-sign.glyphicon-center{:id => "show_children_task_icon_#{task.id}"}
        - if child
          %span.glyphicon.glyphicon-minus.glyphicon-center
      .s1.l1.jot-up-down
        - unless task.first?
          = link_to move_up_task_path(task.id), remote: true do
            %span.glyphicon.glyphicon-circle-arrow-up
        - unless task.last?
          = link_to move_down_task_path(task.id), remote: true do
            %span.glyphicon.glyphicon-circle-arrow-down
      .s10.l10
        =task.position
        = task.name
    .s4.l4{:id => "description_#{task.id}"}
      = truncate("#{task.description}", length: 45, omission: ' ') {link_to "(more)", more_less_task_path(task.id), remote: true  }
    .s5.l5
      
      = f.number_field :percent_complete, value: task.percent_complete,style: 'width:65px', label: "100%++++", class: "input-sm", hide_label: true
       
      = f.select :status, options_for_select([["Hold"], ["Active"], ["Complete"]], "#{task.status}"), {hide_label: true }, wrapper: { class: 'task_table'}, class: "input-sm"
    
      = f.submit wrapper: { class: 'task_table'}, class: "btn btn-default btn-sm"
    
      = f.date_field :finish_date, value: task.finish_date, class: 'form-control input-sm', hide_label: true
      =# l task.finish_date, format: :short if task.finish_date
    .s1.l1
      = link_to task_path(task) do
        %span.glyphicon.glyphicon-eye-open
      =link_to edit_polymorphic_path([parent, task]), remote: true do
        %span.glyphicon.glyphicon-pencil
      = link_to polymorphic_path([parent, task]), remote: true, method: :delete do
        %span.glyphicon.glyphicon-trash
- if task.tasks.count > 0
  %div{:id => "task_#{task.id}_children", :style => "display:none"}
    = render partial: "tasks/task", collection: task.tasks, locals: { parent: task, child: true }

app/views/tasks/destroy.js.erb
$('#task_<%= @task.id %>').remove();

app/views/tasks/edit.js.erb
$('#task_modal').empty();
$('#task_modal').append("<%= j (render partial: 'tasks/shared/task_modal', locals: { new_task: false, parent: @taskable, task: @task }) %>");
$('#task_modal_new').modal('toggle');

app/views/tasks/more_less.js.erb
var l = $('#description_<%= @task.id %> a:contains("(more)")').length

if(l > 0) { 
  $('#description_<%= @task.id %>').replaceWith("<div class='s4 l4' id='description_<%= @task.id %>'>"
    + "<%= @task.description %>" 
    + "<%= escape_javascript link_to '(less)', more_less_task_path(@task.id), remote: 'true' %>"
    + "</div>")
}
else {
  $('#description_<%= @task.id %>').replaceWith("<div class='s4 l4' id='description_<%= @task.id %>'>"
    + "<%= escape_javascript truncate( @task.description, length: 45, omission: ' '){link_to '(more)', more_less_task_path(@task.id), remote: true  } %>" 
    + "</div>")
}

app/views/tasks/move_down.js.erb
$("#task_<%= @task.id %>").remove();
$("#task_<%= @next.id %>").replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: false}) %>");
$("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @next, child: false}) %>").insertBefore("#task_<%= @above_task.id %>");

app/views/tasks/move_up.js.erb
$("#task_<%= @task.id %>").remove();
$("#task_<%= @next.id %>").replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: false}) %>");
$("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @next, child: false}) %>").insertAfter("#task_<%= @above_task.id %>");


/*
var next_visible = $("#task_<%= @task.id %>").prevAll(':visible:first');
var tab_all = $("ul#task_tabs li.active").text().search("All");
callmeman();
function callmeman(){
  if(tab_all >= 0) {

    $("#task_<%= @task.id %>").remove();
    $("#task_<%= @next.id %>").replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: false}) %>");
    $("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @next, child: false}) %>").insertAfter("#task_<%= @task.id %>"); 
  }
  else {
      
    $("#task_<%= @task.id %>").remove();
    $("#task_<%= @next.id %>").replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: false}) %>");
    $("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @next, child: false}) %>").insertAfter("#task_<%= @above_task.id %>");
  }
}
*/

app/views/tasks/new.js.erb
$('#task_modal').empty();
$('#task_modal').append("<%= j (render partial: 'tasks/shared/task_modal', locals: { new_task: true, task: @task }) %>");
$('#task_modal_new').modal('toggle');

app/views/tasks/show_children.js.erb
$("#task_<%= @task.id %>_children").toggle();

if($("#show_children_task_icon_<%= @task.id %>").hasClass("glyphicon-plus-sign")) {
  $("#show_children_task_icon_<%= @task.id %>").removeClass("glyphicon-plus-sign");
  $("#show_children_task_icon_<%= @task.id %>").addClass("glyphicon-minus-sign");
  }
else {
  $("#show_children_task_icon_<%= @task.id %>").addClass("glyphicon-plus-sign");
  $("#show_children_task_icon_<%= @task.id %>").removeClass("glyphicon-minus-sign");
}

app/views/tasks/tab_active.js.erb
$("div[data-type='Active']").show("slow");
$("div[data-type='Hold']").hide("slow");
$("div[data-type='Complete']").hide("slow");
$("li:has(a#tab_active_pill)").addClass("active")
$("li:has(a#tab_hold_pill)").removeClass("active")
$("li:has(a#tab_complete_pill)").removeClass("active")
$("li:has(a#tab_all_pill)").removeClass("active")
$("div.up-down").hide("slow");

app/views/tasks/tab_all.js.erb
$("div[data-type='Active']").show("slow");
$("div[data-type='Hold']").show("slow");
$("div[data-type='Complete']").show("slow");
$("li:has(a#tab_active_pill)").removeClass("active");
$("li:has(a#tab_hold_pill)").removeClass("active");
$("li:has(a#tab_complete_pill)").removeClass("active");
$("li:has(a#tab_all_pill)").addClass("active");
$("div.up-down").show("slow");

app/views/tasks/tab_hold.js.erb
$("div[data-type='Active']").hide("slow");
$("div[data-type='Hold']").show("slow");
$("div[data-type='Complete']").hide("slow");
$("li:has(a#tab_active_pill)").removeClass("active")
$("li:has(a#tab_hold_pill)").addClass("active")
$("li:has(a#tab_complete_pill)").removeClass("active")
$("li:has(a#tab_all_pill)").removeClass("active")

app/views/tasks/update.js.erb
$('#task_modal_new').modal('toggle');
$('.modal-backdrop.fade.in').remove();
$('#task_<%= @task.id %>').replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: false}) %>")

app/views/tasks/update_task.js.erb
if ($("ul#task_tabs li.active:contains('<%= @task.status %>')").length > 0 || $("ul#task_tabs li.active:contains('All')").length > 0 ) {
  $('#task_<%= @task.id %>').replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: @task.task_child? }) %>");
  }
else {
  $('#task_<%= @task.id %>').replaceWith("<%= j (render partial: 'tasks/task', locals: {parent: @taskable, task: @task, child: @task.task_child? }) %>");
  $('#task_<%= @task.id %>').hide();
}