config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  
  devise_for :users, :path => "accounts"

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :ideas do
    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end

    member do
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
=begin
      collection do
        get 'tab_active'
        get 'tab_hold'
        get 'tab_complete'
        get 'tab_all'
      end

      member do
        post :update_task
        get :more_less
      end
=end
    end

    member do
      post :update_status
      post :remove_category
    end
  end

  resources :tasks do
    
    collection do
      get 'tab_active'
      get 'tab_hold'
      get 'tab_complete'
      get 'tab_all'
    end

    member do
      post :update_task
      get :more_less
      get :show_children
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
    end

    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end
  end

  resources :categories do
    resources :notes do
      :notes
    end
  end

  resources :notes do
    resources :notes do
      :notes
    end
  end

  resources :jots do
    member do
      get :move_up
      get :move_down
      get :to_new_idea
      post :to_new_task
    end
  end

end

app/views/shared/_children.html.haml
.panel.panel-default
  #headingTwo.panel-heading{role: "tab"}
    %h4.panel-title
      = link_to "#collapseTwo", 'data-toggle' => "collapse",'aria-expanded'=>"true", 'aria-controls'=>"collapseTwo" do
        %span.glyphicon.glyphicon-tasks
        #{parent.name} - Tasks
      = link_to new_polymorphic_path([parent, @task]), remote: true, class: 'pull-right' do
        %span.glyphicon.glyphicon-plus
        New Task
  #collapseTwo.panel-collapse.collapse{ role: "tabpanel", 'aria-labelledby'=>"headingTwo" }
    .panel-body
      = render partial: 'shared/task_tabs'
      = render partial: 'tasks/shared/task_table', locals: { parent: parent, tasks: @tasks }
.panel.panel-default
  #headingThree.panel-heading{role: "tab"}
    %h4.panel-title
      = link_to "#collapseThree", 'data-toggle' => "collapse",'aria-expanded'=>"true", 'aria-controls'=>"collapseThree" do
        %span.glyphicon.glyphicon-file
        #{parent.name} - Notes
      = link_to new_polymorphic_path([parent, @note]), remote: true, class: 'pull-right' do
        %span.glyphicon.glyphicon-plus
        New Note
  #collapseThree.panel-collapse.collapse{ role: "tabpanel", 'aria-labelledby'=>"headingThree" }
    .panel-body
      #notes.l12.s12
        = render partial: 'notes/note', collection: parent.notes, locals: { parent: parent }
.panel.panel-default
  #headingFour.panel-heading{role: "tab"}
    %h4.panel-title
      = link_to "#collapseFour", 'data-toggle' => "collapse",'aria-expanded'=>"true", 'aria-controls'=>"collapseFour" do
        %span.glyphicon.glyphicon-link
        #{parent.name} - Links
      = link_to new_polymorphic_path([parent, @idea_link]), remote: true, class: 'pull-right' do
        %span.glyphicon.glyphicon-plus
        New Link
  #collapseFour.panel-collapse.collapse{ role: "tabpanel", 'aria-labelledby'=>"headingFour" }
    .panel-body
      = render partial: 'idea_links/shared/idea_link_table', locals: { parent: parent, idea_links: @idea_links }
#modal
#task_modal
#idea_link_modal

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{type: 'button', "data-toggle" => 'collapse', "data-target" => ".navbar-ex1-collapse"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "#", class: 'navbar-brand' do
        %span.glyphicon.glyphicon-tags
        Ideas
    .collapse.navbar-collapse.navbar-ex1-collapse 
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li{:class => "#{'active' if current_page?(ideas_path)}" }
            = link_to ideas_path do
              %span.glyphicon.glyphicon-cog
              Ideas
        - else
          %li{:class => 'active'}
            = link_to "#" do
              %span.glyphicon.glyphicon-home
              Home
        - if user_signed_in?
          %li{:class => "#{'active' if current_page?(jots_path)}" }
            = link_to jots_path do
              %span.glyphicon.glyphicon-comment
              Jots
        - if user_signed_in?
          %li{:class => "#{'active' if current_page?(categories_path)}"}
            = link_to categories_path do
              %span.glyphicon.glyphicon-tags
              Categories
      - if user_signed_in? 
        %ul.nav.navbar-nav.navbar-right 
          %li.dropdown{:class => 'active'}
            %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
              %span.glyphicon.glyphicon-user
              #{current_user.email}
              %b.caret
            %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
              %li
                = link_to 'Edit profile', edit_user_registration_path
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            =link_to new_user_session_path do
              %span.glyphicon.glyphicon-log-in
              Sign in
          %li
            =link_to new_user_registration_path do
              %span.glyphicon.glyphicon-tasks
              Register

app/views/shared/_message_modal.html.haml
#flash_hook  
  .modal.fade{ "id" => "message_modal","tabindex"=>"-1", "role" => "dialog", "aria-labelledby" => "mySmallModalLabel", "aria-hidden" => "true" }
    .modal-dialog
      .modal-content
        %h4
          #{msg}
          %button.close{"type"=>"button", "data-dismiss"=>"modal"}
            %span{"aria-hidden" => "true"}
              %span.glyphicon.glyphicon-remove-circle
            %span.sr-only
              Close

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{bootstrap_flash_type(name)}"){:id => "flash"}
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_task_tabs.html.haml
%ul#task_tabs.nav.nav-pills
  %li.active
    = link_to "All", tab_all_tasks_path, method: 'get', remote: true, id: 'tab_all_pill', :rel => "nofollow"
  %li
    = link_to "Active", tab_active_tasks_path, method: 'get', remote: true, id: 'tab_active_pill', :rel => "nofollow"
  %li
    = link_to "Hold", tab_hold_tasks_path, method: 'get', remote: true, id: 'tab_hold_pill', :rel => "nofollow"
  %li
    = link_to "Complete", tab_complete_tasks_path, method: 'get', remote: true, id: 'tab_complete_pill', :rel => "nofollow"
  