config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  
  devise_for :users, :path => "accounts"

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :ideas do
    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end

    member do
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
=begin
      collection do
        get 'tab_active'
        get 'tab_hold'
        get 'tab_complete'
        get 'tab_all'
      end

      member do
        post :update_task
        get :more_less
      end
=end
    end

    member do
      post :update_status
      post :remove_category
    end
  end

  resources :tasks do
    
    collection do
      get 'tab_active'
      get 'tab_hold'
      get 'tab_complete'
      get 'tab_all'
    end

    member do
      post :update_task
      get :more_less
      get :show_children
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
    end

    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end
  end

  resources :categories do
    resources :notes do
      :notes
    end
  end

  resources :notes do
    resources :notes do
      :notes
    end
  end

  resources :jots do
    member do
      get :move_up
      get :move_down
      get :to_new_idea
      post :to_new_task
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :notes, as: :notable, dependent: :destroy
  has_and_belongs_to_many :ideas, -> { uniq }
  
  validates :name, presence: true
  validates_uniqueness_of :name, case_sensitive: false, scope: :user_id

  extend FriendlyId
  friendly_id :name, use: :scoped, scope: :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_filter :authenticate_user!
  respond_to :js, :html
  before_action  :all_categories, only: [:index, :create, :update, :destroy]
  before_action :set_category, only: [:edit, :update, :show ]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        flash[:success] = "You have created a new category: #{@category.name}"
        format.html { redirect_to categories_path }
        format.js { render action: 'create' }
      else
        flash[:danger] = "There is a problem, try again."
        format.html { render nothing: true }
        format.js { render action: 'edit' }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        flash[:success] = "#{@category.name} category updated."
        format.html { redirect_to categories_path }
        format.js { render action: 'create' }
      else
        flash[:danger] = "Something when wrong."
        #format.html { render 'edit' }
        format.js { render action: 'edit' }
      end
    end
  end

  def destroy
    category = current_user.categories.friendly.find(params[:id])
    name = category.name
    category.destroy
    respond_to do |format|
      flash[:success] = "You have removed category: #{name}."
      format.js { render action: 'destroy'} 
      #format.html { redirect_to categories_path }
    end
  end

  def show
    @notes = @category.notes
    @note = Note.new
    @note.user_id = current_user.id
    @notable = @category
    @ideas = @category.ideas
  end

  def index
  end
  
  private

    def set_category
      @category = current_user.categories.friendly.find(params[:id])
    end

    def all_categories
      @categories = current_user.categories
    end

    def category_params
      params.require(:category).permit(:name, :description, :user_id, :slug)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
%tr{:id => "cat_#{category.id}"}
  %td 
    = link_to category.name, category_path(category)
  %td
  %td
    = category.notes.count
  %td
    = link_to edit_category_path(category), remote: true do
      %span.glyphicon.glyphicon-pencil
    = link_to category_path(category), method: :delete, remote: true, data: { confirm: 'Are you sure?' } do
      %span.glyphicon.glyphicon-trash

app/views/categories/_form.html.haml
= bootstrap_form_for(@category, remote: true) do |f|
  = f.text_field :name
  = f.text_area :description
  = f.hidden_field :user_id, value: current_user.id
  = f.button class: "btn btn-success"
  = link_to "Cancel", :back, {:class=>"btn btn-default"}

app/views/categories/create.js.erb
$('#categories').html("<%= j (render @categories) %>");
$('#category-form').slideUp(350);

app/views/categories/destroy.js.erb
$('#categories').html("<%= j (render @categories) %>");

app/views/categories/edit.js.erb
$('#category-form').html("<%= j (render 'form') %>");
$('#category-form').slideDown(350);

app/views/categories/index.html.haml
%h1.page-header
  %span.glyphicon.glyphicon-tags
  Idea Categories
  %small
    = link_to "Add new category", new_category_path, remote: true
#category-form{style: "display:none;"}
%table.table.table-striped
  %thead
    %tr
      %th
        Category Name
      %th
        No. Ideas
      %th
        No. Notes
      %th
  %tbody#categories
    = render partial: @categories 

app/views/categories/new.js.erb
$('#category-form').html("<%= j (render 'form') %>");
$('#category-form').slideDown(350);

app/views/categories/show.html.haml
%h1.page-header Category: #{@notable.name}
.panel.panel-default
  #headingOne.panel-heading{role: "tab"}
    %h4.panel-title
      = link_to "#{@notable.name} description", "#collapseOne",'data-toggle' => "collapse",'aria-expanded'=>"true", 'aria-controls'=>"collapseOne"
  #collapseOne.panel-collapse.collapse.in{ role: "tabpanel", 'aria-labelledby'=>"headingOne" }
    .panel-body
      #{@notable.description}
.panel.panel-default
  #headingTwo.panel-heading{role: "tab"}
    %h4.panel-title
      = link_to "#{@notable.name} Category Notes", "#collapseTwo", 'data-toggle' => "collapse",'aria-expanded'=>"true", 'aria-controls'=>"collapseTwo"
      = link_to new_polymorphic_path([@notable, @note]), remote: true, class: 'pull-right' do
        %span.glyphicon.glyphicon-plus
        New Note
  #collapseTwo.panel-collapse.collapse{ role: "tabpanel", 'aria-labelledby'=>"headingTwo" }
    .panel-body
      #notes.l12.s12
        = render @notable.notes
.panel.panel-default
  #headingThree.panel-heading{role: "tab"}
    %h4.panel-title
      = link_to "#{@notable.name} Category Ideas", "#collapseThree", 'data-toggle' => "collapse",'aria-expanded'=>"true", 'aria-controls'=>"collapseThree"
      = link_to new_idea_path, remote: true, class: 'pull-right' do
        %span.glyphicon.glyphicon-plus
        New Idea
  #collapseThree.panel-collapse.collapse{ role: "tabpanel", 'aria-labelledby'=>"headingThree" }
    .panel-body
      = render partial: 'ideas/shared/ideas_table', locals:{ ideas: @ideas}
#modal
= #render partial: 'notes/shared/note_modal', locals: { new_note: true, note: @note }

app/views/categories/update.js.erb
$('#categories').html("<%= j (render @categories) %>");
$('#category-form').slideUp(350);