config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  
  devise_for :users, :path => "accounts"

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :ideas do
    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end

    member do
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
=begin
      collection do
        get 'tab_active'
        get 'tab_hold'
        get 'tab_complete'
        get 'tab_all'
      end

      member do
        post :update_task
        get :more_less
      end
=end
    end

    member do
      post :update_status
      post :remove_category
    end
  end

  resources :tasks do
    
    collection do
      get 'tab_active'
      get 'tab_hold'
      get 'tab_complete'
      get 'tab_all'
    end

    member do
      post :update_task
      get :more_less
      get :show_children
      get :move_up
      get :move_down
    end

    resources :tasks do
      :tasks
    end

    resources :notes do
      :notes
    end

    resources :idea_links do
      :idea_links
    end
  end

  resources :categories do
    resources :notes do
      :notes
    end
  end

  resources :notes do
    resources :notes do
      :notes
    end
  end

  resources :jots do
    member do
      get :move_up
      get :move_down
      get :to_new_idea
      post :to_new_task
    end
  end

end

app/models/jot.rb
class Jot < ActiveRecord::Base
  belongs_to :user
  validates :context, presence: true
  validates :status, :inclusion => { :in => %w(Hold Active Complete) }
  acts_as_list scope: :user
end

app/controllers/jots_controller.rb
class JotsController < ApplicationController
  before_action :authenticate_user!
  respond_to :js, :html
  
  def new
    @jot = Jot.new
  end

  def index
    @jots = current_user.jots
  end

  def create
    @jot = Jot.new(jot_params)

    if @jot.save
      @jot.move_to_top
      flash[:success] = "You created a new Jot. Good luck!"
    else
      flash[:danger] = "Something went wrong, try again."
      render :edit
    end
    
    @jots = current_user.jots
  end

  def edit
    @jot = current_user.jots.find(params[:id])
  end

  def update
    @jot = current_user.jots.find(params[:id])
    @jots = current_user.jots

    if @jot.update(jot_params)
      flash[:success] = "Jot #{@jot.position} idea updated."
      render :update
    else
      flash[:danger] = "Something went wrong, try again."
      render :edit
    end
  end

  def destroy
    @jot = current_user.jots.find(params[:id])

    if @jot.destroy
      flash[:success] = "Jot removed."

    else
      flash[:danger] = "Failed to remove jot."
    end  
  end

  def to_new_idea
    @jot = current_user.jots.find(params[:id])
    @idea = current_user.ideas.create(name: @jot.context, description: @jot.context, status: "Hold")
    
    if @idea.save
      flash[:success] = "Idea created from Jot."
      render :js => "window.location.href='"+ideas_path+"'"
    else
      flash[:danger] = "Something went wrong, try again."
      render nothing: true
    end
  end

  def to_new_task

    @jot = current_user.jots.find(params[:id])
    @parent = current_user.ideas.find(params[:idea_id]) 
    @task = Task.create(user_id: current_user.id, name: @jot.context, status: "Hold", taskable_type: "Idea", taskable_id: @parent.id)
    #@parent.tasks << Task.create(user_id: current_user.id, name: @jot.context, status: "Hold")
    if @task.save
      flash[:success] = "Task created from Jot."
      render :js => "window.location.href='"+task_path(@task)+"'"
      #redirect_to task_path(@task)
    else
      flash[:danger] = "Something went wrong, try again."
    end
  end

  def move_up
    @jot = current_user.jots.find(params[:id])
    
    if @jot.first?
      flash[:danger] = "Jot is already at the top."
      render nothing: true
    else
      @jot.move_higher
      @next_jot = @jot.lower_item
      flash[:success] = "Jot moved up list."
    end
  end

  def move_down
    @jot = current_user.jots.find(params[:id])
    if @jot.last?
      flash[:danger] = "Jot is already at the bottom."
      render nothing: true
    else
      @jot.move_lower
      @next_jot = @jot.higher_item
      flash[:success] = "Jot moved down list."
    end
  end

  private

  def jot_params
    params.require(:jot).permit(:context, :status, :user_id, :id)
  end
end

app/helpers/jots_helper.rb
module JotsHelper

  def row_class(jot)
    case jot.status
    when "Hold"
      return "warning"
    when "Complete"
      return "info"
    else
      return "success"
    end
  end
end

app/views/jots/_form.html.haml
= bootstrap_form_for(@jot, remote: true) do |f|
  = f.text_area :context
  = f.select :status, options_for_select([["Hold"], ["Active"], ["Complete"]], "#{@jot.status}"), { label: "Update Idea Status " }, { class: "selectpicker" }
  = f.hidden_field :user_id, value: current_user.id
  = f.button class: "btn btn-success"
  = link_to "Cancel", :back, {:class=>"btn btn-default"}

app/views/jots/_jot.html.haml
%tr{:id => "jot_#{jot.id}", class: row_class(jot)}
  %td.jot-up-down
    - unless jot.first?
      = link_to move_up_jot_path(jot), remote: true do
        %span.glyphicon.glyphicon-circle-arrow-up
    - unless jot.last?
      = link_to move_down_jot_path(jot), remote: true do
        %span.glyphicon.glyphicon-circle-arrow-down
  %td
    #{jot.context}
  %td
    = bootstrap_form_tag(url: "#{to_new_task_jot_path(jot)}", layout: :inline, remote: true, :html => {:class => "form-jot"}) do |f|
      = link_to to_new_idea_jot_path(jot),remote: true, class: "btn btn-default btn-sm" do
        Make Idea
        %span.glyphicon.glyphicon-chevron-right
      = f.select('idea_id', current_user.ideas.collect { |p| [p.name, p.id] }, {hide_label: true}, {class: "input-sm", id: "idea_#{jot.id}" } )
      = button_tag(type: "submit", class: "btn btn-default btn-sm") do
        To Task
        %span.glyphicon.glyphicon-chevron-right
  %td
    #{ time_ago_in_words(jot.created_at) } ago
  %td
    .btn-group.btn-group-sm
      = link_to edit_jot_path(jot), class: "btn btn-primary", remote: true do
        %span.glyphicon.glyphicon-pencil
      = link_to jot_path(jot), method: :delete, class: "btn btn-primary", remote: true, data: { confirm: 'Are you sure?' } do
        %span.glyphicon.glyphicon-trash

app/views/jots/create.js.erb
$('#jots').html("<%= j (render @jots) %>");
$('#jot-form').slideUp(350);

app/views/jots/destroy.js.erb
$('#jot_<%= @jot.id %>').remove();

app/views/jots/edit.js.erb
$('#jot-form').html("<%= j (render 'form') %>");
$('#jot-form').slideDown(350);

app/views/jots/index.html.haml
%h1.page-header
  %span.glyphicon.glyphicon-comment
  Jots
  %small
    = link_to "Add new jot", new_jot_path, remote: true
= render partial: 'jots/shared/jots_table', locals:{ jots: @jots}

app/views/jots/move_down.js.erb
var next = $("#jot_<%= @jot.id %>").next();
$("#jot_<%= @jot.id %>").remove();
$(next).replaceWith("<%= j (render partial: 'jots/jot', locals: { jot: @jot }) %>");
$("<%= j (render partial: 'jots/jot', locals: { jot: @next_jot }) %>").insertBefore("#jot_<%= @jot.id %>");

app/views/jots/move_up.js.erb
var next = $("#jot_<%= @jot.id %>").prev();
$("#jot_<%= @jot.id %>").remove();
$(next).replaceWith("<%= j (render partial: 'jots/jot', locals: { jot: @jot }) %>");
$("<%= j (render partial: 'jots/jot', locals: { jot: @next_jot }) %>").insertAfter("#jot_<%= @jot.id %>");

app/views/jots/new.js.erb
$('#jot-form').html("<%= j (render 'form') %>");
$('#jot-form').slideDown(350);

app/views/jots/update.js.erb
$('#jots').html("<%= j (render @jots) %>");
$('#jot-form').slideUp(350);